#!/usr/bin/env bash

#: exec_target = cli

## Initialize/reinstall site
##
## Usage: fin init-site

# Abort if anything fails
set -e

#-------------------------- Settings --------------------------------

# PROJECT_ROOT and DOCROOT are set as env variables in cli
SITE_DIRECTORY="default"
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
SITEDIR_PATH="${DOCROOT_PATH}/sites/${SITE_DIRECTORY}"

#-------------------------- END: Settings --------------------------------

#-------------------------- Helper functions --------------------------------

# Copy a settings file.
# Skips if the destination file already exists.
# @param $1 source file
# @param $2 destination file
copy_settings_file()
{
	local source="$1"
	local dest="$2"

	if [[ ! -f $dest ]]; then
		echo "Copying ${dest}..."
		cp $source $dest
	else
		echo "${dest} already in place."
	fi
}

#-------------------------- END: Helper functions --------------------------------

#-------------------------- Functions --------------------------------

# Initialize local settings files
init_settings ()
{
	# Copy from settings templates
	copy_settings_file "${SITEDIR_PATH}/default.settings.local.php" "${SITEDIR_PATH}/settings.local.php"
}

# Fix file/folder permissions
fix_permissions ()
{
	echo "Making site directory writable..."
	chmod 755 "${SITEDIR_PATH}"
}

# Install site
site_install ()
{
	cd $DOCROOT_PATH

	# We disable email sending here so site-install does not return an error
	PHP_OPTIONS="-d sendmail_path=`which true`" drush site-install -y --site-name='My Drupal 8 Site'
}

# Composer Install
composer_install ()
{
  cd $PROJECT_ROOT
  composer global require hirak/prestissimo:^0.3
  composer install
}

polymer_install() {
    npm install -g polymer-cli;
}

bower_install() {
    npm install -g bower;
}

theme_install()
{
    echo "Installing Obra-Theme..."
    cd $PROJECT_ROOT;
    git submodule init;
    git submodule update;

#    echo "Enabling Obra-Theme as default theme (NOTE: not Admin)..."
#    cd $DOCROOT_PATH;
#    drush config-set system.theme default obra-theme -y;

    echo "Enable Obra-Theme manually within Drupal 8 UI. Auto-set to be added..."
}

theme_build()
{
    cd $DOCROOT_PATH/themes/custom/obra-theme;
    bower install;
    cd $DOCROOT_PATH/themes/custom/obra-theme/elements;
    polymer build;
}

#-------------------------- END: Functions --------------------------------

#-------------------------- Execution --------------------------------

# Project initialization steps
composer_install;
fix_permissions;
init_settings;
time site_install;
polymer_install;
bower_install;
theme_install;
theme_build;

#-------------------------- END: Execution --------------------------------
