<?php

/**
 * @file
 * Contains obra_theme_blocks.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function obra_theme_blocks_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the obra_theme_blocks module.
    case 'help.page.obra_theme_blocks':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Default placement of blocks for the Obra theme.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function obra_theme_blocks_theme() {
  return [
    'obra_theme_blocks' => [
      'render element' => 'children',
    ],
  ];
}
